In [1]:
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)

2.7.0


# Operation on Tensors
* tf.constant()
* tf.variable()

In [3]:
# Create a constant tensor
x = tf.constant([2,3,4])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [5]:
# Create a variable
v = tf.Variable(2.0, dtype=tf.float32, name='my_variable')
v

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=2.0>

In [6]:
# Assign value to variable
v.assign(45.2)
v

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=45.2>

## Operations mathematical
* add
* subtract
* multiply
* divide

In [9]:
v.assign_add(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=49.2>

In [10]:
v.assign_sub(10)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=39.2>

In [12]:
tf.multiply(v,2)

<tf.Tensor: shape=(), dtype=float32, numpy=78.4>

In [13]:
tf.divide(v,2)

<tf.Tensor: shape=(), dtype=float32, numpy=19.6>

## Pointwise operations
* tf.add()
* tf.subtract()
* tf.multiply()
* tf.math.*
* tf.math.exp()

In [14]:
# Create constant tensor
c1 = tf.constant([1,2,3,4,5])
c2 = tf.constant([10,20,30,40,50])
c_multiply = tf.multiply(c1, c2)
c_multiply2 = c1 * c2
print("c1: ", c_multiply)
print("c2: ", c_multiply2)

c1:  tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)
c2:  tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)


In [15]:
# create constant variable
# define the data type first if the operations requires specific data type
a = tf.constant([1,2,3],dtype=tf.float32)
b = tf.math.exp(a)
print("b: ",b)

b:  tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)


## Numpy Interoperability
TensorFlow can take native python types and Numpy arrays as operands

In [16]:
# native python list
list_a = [1,2]
list_b = [3,4]
array_a = np.array([1,2])
array_b = np.array([3,4])

In [17]:
tf.add(list_a,list_b)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [18]:
tf.add(array_a,array_b)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

### Convert a "native TF tensor" to a "numpy array"

In [19]:
tensor_a = tf.constant([1,2,3])
convert_np_array = tensor_a.numpy()
convert_np_array

array([1, 2, 3])