In [1]:
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)

2.7.0


# Operation on Tensors
* tf.constant()
* tf.variable()

In [3]:
# Create a constant tensor
x = tf.constant([2,3,4])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [5]:
# Create a variable
v = tf.Variable(2.0, dtype=tf.float32, name='my_variable')
v

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=2.0>

In [6]:
# Assign value to variable
v.assign(45.2)
v

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=45.2>

## Operations mathematical
* add
* subtract
* multiply
* divide

In [9]:
v.assign_add(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=49.2>

In [10]:
v.assign_sub(10)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=39.2>

In [12]:
tf.multiply(v,2)

<tf.Tensor: shape=(), dtype=float32, numpy=78.4>

In [13]:
tf.divide(v,2)

<tf.Tensor: shape=(), dtype=float32, numpy=19.6>

## Pointwise operations
* tf.add()
* tf.subtract()
* tf.multiply()
* tf.math.*